# TCL File Generated by Component Editor 10.1
# Sun Jan 23 01:18:19 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | TERASIC_CAMERA "TERASIC_CAMERA" v1.0
# | null 2011.01.23.01:18:19
# | 
# | 
# | D:/svn/DE2_115_WDR_CAMERA/ip/TERASIC_CAMERA/TERASIC_CAMERA.v
# | 
# |    ./TERASIC_CAMERA.v syn, sim
# |    ./CAMERA_RGB.v syn, sim
# |    ./CAMERA_Bayer.v syn, sim
# |    ./Bayer2RGB.v syn, sim
# |    ./Bayer_LineBuffer.v syn, sim
# |    ./rgb_fifo.v syn, sim
# |    ./add2.v syn, sim
# |    ./add4.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module TERASIC_CAMERA
# | 
set_module_property NAME TERASIC_CAMERA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME TERASIC_CAMERA
set_module_property TOP_LEVEL_HDL_FILE TERASIC_CAMERA.v
set_module_property TOP_LEVEL_HDL_MODULE TERASIC_CAMERA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file TERASIC_CAMERA.v {SYNTHESIS SIMULATION}
add_file CAMERA_RGB.v {SYNTHESIS SIMULATION}
add_file CAMERA_Bayer.v {SYNTHESIS SIMULATION}
add_file Bayer2RGB.v {SYNTHESIS SIMULATION}
add_file Bayer_LineBuffer.v {SYNTHESIS SIMULATION}
add_file rgb_fifo.v {SYNTHESIS SIMULATION}
add_file add2.v {SYNTHESIS SIMULATION}
add_file add4.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter VIDEO_W INTEGER 800
set_parameter_property VIDEO_W DEFAULT_VALUE 800
set_parameter_property VIDEO_W DISPLAY_NAME VIDEO_W
set_parameter_property VIDEO_W TYPE INTEGER
set_parameter_property VIDEO_W UNITS None
set_parameter_property VIDEO_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_W AFFECTS_GENERATION false
set_parameter_property VIDEO_W HDL_PARAMETER true
add_parameter VIDEO_H INTEGER 600
set_parameter_property VIDEO_H DEFAULT_VALUE 600
set_parameter_property VIDEO_H DISPLAY_NAME VIDEO_H
set_parameter_property VIDEO_H TYPE INTEGER
set_parameter_property VIDEO_H UNITS None
set_parameter_property VIDEO_H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_H AFFECTS_GENERATION false
set_parameter_property VIDEO_H HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end CAMERA_D export Input 12
add_interface_port conduit_end CAMERA_FVAL export Input 1
add_interface_port conduit_end CAMERA_LVAL export Input 1
add_interface_port conduit_end CAMERA_PIXCLK export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_reset
set_interface_property avalon_streaming_source associatedReset clock_reset_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1

set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source st_data data Output 24
add_interface_port avalon_streaming_source st_sop startofpacket Output 1
add_interface_port avalon_streaming_source st_eop endofpacket Output 1
add_interface_port avalon_streaming_source st_ready ready Input 1
add_interface_port avalon_streaming_source st_valid valid Output 1
# | 
# +-----------------------------------
