version: "3.8"
services:
  # Node.js application
  node:
    container_name: node
    build:
      context: ./MQTT_Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
        mysql_v2:
          condition: service_healthy
    volumes:
      - ./MQTT_Backend:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=testdb

  # MySQL database
  mysql_v2:
    container_name: mysql_v2
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      timeout: 5s
      retries: 1
#    networks:
#       - app-tier

# React frontend
#frontend:
# build:
#  context: ./frontend
# dockerfile: Dockerfile
#ports:
# - 3000:3000
#volumes:
# - ./frontend:/app
#networks:
#   - app-tier
