# This script has the logic to create a summary report
source C:/intelFPGA_lite/18.1/hls/share/lib/tcl/hls_qii_compile_report.tcl
source C:/intelFPGA_lite/18.1/hls/share/lib/tcl/hls_quartus_html_report.tcl
# These are generated by i++ based on the components
set show_clk2x   0
set components   [list rgb_to_hsv]
# This is where we'll generate the report
set report_name  "../reports/lib/json/quartus.json"
# These get sent to the script by Quartus
set project_name [lindex $quartus(args) 1]
set project_rev  [lindex $quartus(args) 2]
# This call creates the report
generate_report $project_name $project_rev $report_name $show_clk2x $components
update_html_report_data
