// tb_rgb_to_hv_inst.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module tb_rgb_to_hv_inst (
		input  wire [7:0]  blue,       //       blue.data
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		input  wire        clock,      //      clock.clk
		input  wire [7:0]  green,      //      green.data
		input  wire [7:0]  red,        //        red.data
		input  wire        resetn,     //      reset.reset_n
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [26:0] returndata  // returndata.data
	);

	rgb_to_hv_internal rgb_to_hv_internal_inst (
		.clock      (clock),      //      clock.clk
		.resetn     (resetn),     //      reset.reset_n
		.start      (start),      //       call.valid
		.busy       (busy),       //           .stall
		.done       (done),       //     return.valid
		.stall      (stall),      //           .stall
		.returndata (returndata), // returndata.data
		.red        (red),        //        red.data
		.green      (green),      //      green.data
		.blue       (blue)        //       blue.data
	);

endmodule
